force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <formula>Draws__c +  Wins__c +  Losses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matches Played</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(  Wins__c  * 3 ) +  Draws__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Tournament_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Group A</fullName>
    </customValue>
    <customValue>
        <fullName>Group B</fullName>
    </customValue>
    <customValue>
        <fullName>Group C</fullName>
    </customValue>
    <customValue>
        <fullName>Group D</fullName>
    </customValue>
    <customValue>
        <fullName>Group E</fullName>
    </customValue>
    <customValue>
        <fullName>Group F</fullName>
    </customValue>
    <customValue>
        <fullName>Group G</fullName>
    </customValue>
    <customValue>
        <fullName>Group H</fullName>
    </customValue>
    <masterLabel>Tournament Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/apiResources/TeamApiResource.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@RestResource(urlMapping='/v1/tournaments/*/teams/*')
global with sharing class TeamApiResource {
  @HttpGet
  global static List<TournamentDTO.Team> handleGetRequests() {
    RestRequest req = RestContext.request;
    Logger.info('Request for api: ' + req.requestURI);
    String[] uriParts = req.requestURI.split('/');

    try {
      String tournamentCode = uriParts[3];

      if (uriParts.size() < 6) {
        // Handle /v1/tournaments/{code}/teams (collection)
        return getTeams(tournamentCode);
      } else {
        // Handle /v1/tournaments/{code}/teams/{teamCode} (item)
        String teamCode = uriParts[5];

        return getTeam(tournamentCode, teamCode);
      }
    } catch (Exception e) {
      RestContext.response.statusCode = 500;

      Logger.error('Error occurred in api: ' + req.requestURI, e);

      return null;
    } finally {
      Logger.saveLog();
    }
  }

  private static List<TournamentDTO.Team> getTeams(String tournamentCode) {
    List<Tournament_Team__c> tournamentTeams = [
      SELECT Team__r.Code__c, Team__r.Name
      FROM Tournament_Team__c
      WHERE Tournament__r.Code__c = :tournamentCode
      WITH USER_MODE
    ];

    List<TournamentDTO.Team> dtoList = new List<TournamentDTO.Team>();

    for (Tournament_Team__c tournamentTeam : tournamentTeams) {
      dtoList.add(
        new TournamentDTO.Team(
          tournamentTeam.Team__r.Code__c,
          tournamentTeam.Team__r.Name
        )
      );
    }

    return dtoList;
  }

  private static List<TournamentDTO.Team> getTeam(
    String tournamentCode,
    String teamCode
  ) {
    List<Tournament_Team__c> tournamentTeams = [
      SELECT
        Group__c,
        Team__r.Code__c,
        Team__r.Name,
        Goals_For__c,
        Goals_Against__c,
        Goal_Difference__c,
        Wins__c,
        Losses__c,
        Draws__c,
        Matches_Played__c,
        Points__c,
        Eliminated__c
      FROM Tournament_Team__c
      WHERE
        Tournament__r.Code__c = :tournamentCode
        AND Team__r.Code__c = :teamCode
      WITH USER_MODE
      LIMIT 1
    ];

    if (tournamentTeams.isEmpty()) {
      RestContext.response.statusCode = 404;

      Logger.info(
        'Team ' + teamCode + ' in tournament ' + tournamentCode + ' not found'
      );

      return null;
    }

    return new List<TournamentDTO.Team>{
      new TournamentDTO.Team(tournamentTeams[0])
    };
  }
}