force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Tournament_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Group A</fullName>
    </customValue>
    <customValue>
        <fullName>Group B</fullName>
    </customValue>
    <customValue>
        <fullName>Group C</fullName>
    </customValue>
    <customValue>
        <fullName>Group D</fullName>
    </customValue>
    <customValue>
        <fullName>Group E</fullName>
    </customValue>
    <customValue>
        <fullName>Group F</fullName>
    </customValue>
    <customValue>
        <fullName>Group G</fullName>
    </customValue>
    <customValue>
        <fullName>Group H</fullName>
    </customValue>
    <masterLabel>Tournament Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/apiResources/TeamApiResourceTest.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@isTest
private class TeamApiResourceTest {
  @isTest
  static void testHandleGetRequestsCollection() {
    // Create test data
    String tournamentCode = 'TEST';
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = tournamentCode,
      Start_Date__c = Date.today()
    );
    insert tournament;
    List<Team__c> teams = new List<Team__c>();
    for (Integer i = 0; i < 3; i++) {
      teams.add(new Team__c(Name = 'Test Team ' + i, Code__c = 'T' + i));
    }
    insert teams;
    List<Tournament_Team__c> tournamentTeams = new List<Tournament_Team__c>();
    for (Team__c team : teams) {
      tournamentTeams.add(
        new Tournament_Team__c(
          Tournament__c = tournament.Id,
          Team__c = team.Id,
          Group__c = GroupUtility.GROUP_A
        )
      );
    }
    TriggerHandler.bypass('TournamentTeamTriggerHandler');
    insert tournamentTeams;
    // Simulate HTTP GET request for collection
    RestRequest req = new RestRequest();
    req.requestURI = '/v1/tournaments/' + tournamentCode + '/teams';
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestResponse res = new RestResponse();
    RestContext.response = res;
    List<TournamentDTO.Team> result = TeamApiResource.handleGetRequests();
    // Verify the results
    System.assertEquals(3, result.size(), 'Three teams should be returned');
    for (Integer i = 0; i < 3; i++) {
      System.assertEquals('T' + i, result[i].code, 'Team code should match');
      System.assertEquals(
        'Test Team ' + i,
        result[i].name,
        'Team name should match'
      );
    }
  }
  @isTest
  static void testHandleGetRequestsItem() {
    // Create test data
    String tournamentCode = 'TEST';
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = tournamentCode,
      Start_Date__c = Date.today()
    );
    insert tournament;
    String teamCode = 'TM';
    String teamName = 'Test Team';
    Team__c team = new Team__c(Name = teamName, Code__c = teamCode);
    insert team;
    Tournament_Team__c tournamentTeam = new Tournament_Team__c(
      Tournament__c = tournament.Id,
      Team__c = team.Id,
      Group__c = GroupUtility.GROUP_A,
      Goals_For__c = 10,
      Goals_Against__c = 5,
      Wins__c = 1,
      Losses__c = 1,
      Draws__c = 1,
      Eliminated__c = false
    );
    TriggerHandler.bypass('TournamentTeamTriggerHandler');
    insert tournamentTeam;
    // Simulate HTTP GET request for item
    RestRequest req = new RestRequest();
    req.requestURI = '/v1/tournaments/' + tournamentCode + '/teams/' + teamCode;
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestResponse res = new RestResponse();
    RestContext.response = res;
    List<TournamentDTO.Team> result = TeamApiResource.handleGetRequests();
    // Verify the results
    System.assertEquals(1, result.size(), 'One team should be returned');
    TournamentDTO.Team returnedTeam = result[0];
    System.assertEquals(teamCode, returnedTeam.code, 'Team code should match');
    System.assertEquals(teamName, returnedTeam.name, 'Team name should match');
    System.assertEquals(
      GroupUtility.GROUP_A,
      returnedTeam.stats.groupName,
      'Group should match'
    );
    System.assertEquals(
      10,
      returnedTeam.stats.goalsFor,
      'Goals For should match'
    );
    System.assertEquals(
      5,
      returnedTeam.stats.goalsAgainst,
      'Goals Against should match'
    );
    System.assertEquals(
      5,
      returnedTeam.stats.goalsDifference,
      'Goal Difference should match'
    );
    System.assertEquals(1, returnedTeam.stats.wins, 'Wins should match');
    System.assertEquals(1, returnedTeam.stats.losses, 'Losses should match');
    System.assertEquals(1, returnedTeam.stats.draws, 'Draws should match');
    System.assertEquals(
      3,
      returnedTeam.stats.matchesPlayed,
      'Matches Played should match'
    );
    System.assertEquals(4, returnedTeam.stats.points, 'Points should match');
    System.assertEquals(
      false,
      returnedTeam.stats.eliminated,
      'Eliminated should match'
    );
  }

  @isTest
  static void testHandleGetRequestsItemNotFound() {
    // Create test data
    String tournamentCode = 'TEST';
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = tournamentCode,
      Start_Date__c = Date.today()
    );
    insert tournament;
    // Simulate HTTP GET request for a non-existent team
    RestRequest req = new RestRequest();
    req.requestURI =
      '/v1/tournaments/' +
      tournamentCode +
      '/teams/NON_EXISTENT_TEAM';
    req.httpMethod = 'GET';
    RestContext.request = req;
    RestResponse res = new RestResponse();
    RestContext.response = res;
    List<TournamentDTO.Team> result = TeamApiResource.handleGetRequests();
    // Verify the results
    System.assertEquals(null, result, 'No team should be returned');
    System.assertEquals(
      404,
      RestContext.response.statusCode,
      'Status code should be 404'
    );
  }
}