force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/utilities/TournamentStageUtilityTest.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@isTest
private class TournamentStageUtilityTest {
  @isTest
  static void testTournamentInGroupStage() {
    // Create test data
    Tournament__c groupStageTournament = new Tournament__c(
      Name = 'Test Tournament Group',
      Code__c = 'TESTGRP',
      Start_Date__c = Date.today(),
      Stage__c = TournamentStageUtility.GROUP_STAGE
    );
    Tournament__c knockoutStageTournament = new Tournament__c(
      Name = 'Test Tournament KO',
      Code__c = 'TESTKO',
      Start_Date__c = Date.today(),
      Stage__c = TournamentStageUtility.KNOCKOUT_STAGE
    );
    // Insert the test data
    insert new List<Tournament__c>{
      groupStageTournament,
      knockoutStageTournament
    };
    // Test cases
    // Verify that the tournament is in the group stage
    System.assert(
      TournamentStageUtility.tournamentInGroupStage(groupStageTournament),
      'The tournament should be in the group stage'
    );
    System.assert(
      !TournamentStageUtility.tournamentInGroupStage(knockoutStageTournament),
      'The tournament should not be in the group stage'
    );
  }
  @isTest
  static void testTournamentInKnockoutStage() {
    // Create test data
    Tournament__c groupStageTournament = new Tournament__c(
      Name = 'Test Tournament Group',
      Code__c = 'TESTGRP',
      Start_Date__c = Date.today(),
      Stage__c = TournamentStageUtility.GROUP_STAGE
    );
    Tournament__c knockoutStageTournament = new Tournament__c(
      Name = 'Test Tournament KO',
      Code__c = 'TESTKO',
      Start_Date__c = Date.today(),
      Stage__c = TournamentStageUtility.KNOCKOUT_STAGE
    );
    // Insert the test data
    insert new List<Tournament__c>{
      groupStageTournament,
      knockoutStageTournament
    };
    // Test cases
    // Verify that the tournament is in the knockout stage
    System.assert(
      TournamentStageUtility.tournamentInKnockoutStage(knockoutStageTournament),
      'The tournament should be in the knockout stage'
    );
    System.assert(
      !TournamentStageUtility.tournamentInKnockoutStage(groupStageTournament),
      'The tournament should not be in the knockout stage'
    );
  }
}