force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/utilities/TournamentStageUtility.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-08-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class TournamentStageUtility {
  // NOTE: these values are part of the picklist field Stage__c of the Tournament__c object
  // so they must be kept in sync with the picklist values
  public final static String GROUP_STAGE = 'Group Stage';
  public final static String KNOCKOUT_STAGE = 'Knockout Stage';

  public static Boolean tournamentInGroupStage(Tournament__c tournament) {
    return tournament.Stage__c == GROUP_STAGE;
  }

  public static Boolean tournamentInKnockoutStage(Tournament__c tournament) {
    return tournament.Stage__c == KNOCKOUT_STAGE;
  }
}