force-app/main/default/objects/Tournament_Configuration__c/Tournament_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Tournament Configuration</label>
</CustomObject>

force-app/main/default/objects/Tournament_Configuration__c/fields/Group_Stage_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Group_Stage_Prefix__c</fullName>
    <defaultValue>&quot;Group Stage&quot;</defaultValue>
    <label>Group Stage Prefix</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tournament_Configuration__c/fields/Knockout_Stage_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Knockout_Stage_Prefix__c</fullName>
    <defaultValue>&quot;Knockout Stage&quot;</defaultValue>
    <label>Knockout Stage Prefix</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tournament_Configuration__c/fields/Max_Group_Matches_Per_Team__c.field-meta.xml
<CustomField>
    <fullName>Max_Group_Matches_Per_Team__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Max Group Matches Per Team</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Configuration__c/fields/Max_Teams_Per_Group__c.field-meta.xml
<CustomField>
    <fullName>Max_Teams_Per_Group__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Max Teams Per Group</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TournamentConfigurationUtility.cls
public with sharing class TournamentConfigurationUtility {
  private Tournament_Configuration__c orgDefaults;

  public TournamentConfigurationUtility() {
    orgDefaults = Tournament_Configuration__c.getOrgDefaults();
  }

  public Integer getDefaultMaxTeamsPerGroup() {
    return (Integer) orgDefaults.Max_Teams_Per_Group__c;
  }

  public Integer getDefaultMaxGroupMatchesPerTeam() {
    return (Integer) orgDefaults.Max_Group_Matches_Per_Team__c;
  }

  public String getDefaultKnockoutStagePrefix() {
    return (String) orgDefaults.Knockout_Stage_Prefix__c;
  }

  public String getDefaultGroupStagePrefix() {
    return (String) orgDefaults.Group_Stage_Prefix__c;
  }
}