force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Home_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/apiResources/MatchApiResource.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@RestResource(urlMapping='/v1/tournaments/*/matches/*')
global with sharing class MatchApiResource {
  @HttpGet
  global static List<TournamentDTO.Match> handleGetRequests() {
    RestRequest req = RestContext.request;
    String[] uriParts = req.requestURI.split('/');

    try {
      String tournamentCode = uriParts[3];

      if (uriParts.size() < 6) {
        // Handle /v1/tournaments/{code}/matches (collection)
        return getTournamentMatches(tournamentCode);
      } else {
        // Handle /v1/tournaments/{code}/matches/{teamCode} (item)
        String teamCode = uriParts[5];

        return getTeamMatches(tournamentCode, teamCode);
      }
    } catch (Exception e) {
      RestContext.response.statusCode = 500;

      Logger.error('Error occurred in api: ' + req.requestURI, e);

      return null;
    } finally {
      Logger.saveLog();
    }
  }

  private static List<TournamentDTO.Match> getTournamentMatches(
    String tournamentCode
  ) {
    List<Match__c> matches = [
      SELECT
        Stage__c,
        Date__c,
        Home_Team__r.Code__c,
        Home_Team_Goals__c,
        Away_Team__r.Code__c,
        Away_Team_Goals__c,
        Winner_Team__r.Code__c,
        Draw__c
      FROM Match__c
      WHERE Tournament__r.Code__c = :tournamentCode
      WITH USER_MODE
    ];

    List<TournamentDTO.Match> dtoList = new List<TournamentDTO.Match>();

    for (Match__c match : matches) {
      dtoList.add(new TournamentDTO.Match(match));
    }

    return dtoList;
  }

  private static List<TournamentDTO.Match> getTeamMatches(
    String tournamentCode,
    String teamCode
  ) {
    List<Match__c> matches = [
      SELECT
        Stage__c,
        Date__c,
        Home_Team__r.Code__c,
        Home_Team_Goals__c,
        Away_Team__r.Code__c,
        Away_Team_Goals__c,
        Winner_Team__r.Code__c,
        Draw__c
      FROM Match__c
      WHERE
        Tournament__r.Code__c = :tournamentCode
        AND (Home_Team__r.Code__c = :teamCode
        OR Away_Team__r.Code__c = :teamCode)
      WITH USER_MODE
    ];

    List<TournamentDTO.Match> dtoList = new List<TournamentDTO.Match>();

    for (Match__c match : matches) {
      dtoList.add(new TournamentDTO.Match(match));
    }

    return dtoList;
  }
}