force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Tournament_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Group A</fullName>
    </customValue>
    <customValue>
        <fullName>Group B</fullName>
    </customValue>
    <customValue>
        <fullName>Group C</fullName>
    </customValue>
    <customValue>
        <fullName>Group D</fullName>
    </customValue>
    <customValue>
        <fullName>Group E</fullName>
    </customValue>
    <customValue>
        <fullName>Group F</fullName>
    </customValue>
    <customValue>
        <fullName>Group G</fullName>
    </customValue>
    <customValue>
        <fullName>Group H</fullName>
    </customValue>
    <masterLabel>Tournament Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controllers/GroupStageOverviewController.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-02-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class GroupStageOverviewController {
  @AuraEnabled
  public static Map<String, GroupOverview> getGroupStageOverview(
    Id tournamentId
  ) {
    Map<String, GroupOverview> overviewByGroup = new Map<String, GroupOverview>();

    List<Match__c> groupMatches = MatchUtility.getOverviewMatches(
      tournamentId,
      StageUtility.GROUP_STAGES
    );
    List<Tournament_Team__c> tournamentTeams = TournamentTeamUtility.getOverviewTournamentTeams(
      new Set<Id>{ tournamentId }
    );

    Map<Id, String> groupsByTeam = new Map<Id, String>();

    for (String groupName : GroupUtility.GROUPS) {
      GroupOverview groupOverview = new GroupOverview(groupName);

      for (Tournament_Team__c tournamentTeam : tournamentTeams) {
        GroupStageOverviewController.addTeamStats(
          groupOverview,
          tournamentTeam,
          groupsByTeam
        );
      }

      for (Match__c match : groupMatches) {
        if (groupsByTeam.get(match.Home_Team__c) == groupName) {
          groupOverview.addMatchOverview(new MatchOverview(match));
        }
      }

      if (!overviewByGroup.containsKey(groupName)) {
        overviewByGroup.put(groupName, groupOverview);
      }
    }

    return overviewByGroup;
  }

  private static void addTeamStats(
    GroupOverview groupOverview,
    Tournament_Team__c tournamentTeam,
    Map<Id, String> groupsByTeam
  ) {
    if (!groupsByTeam.containsKey(tournamentTeam.Team__c)) {
      groupsByTeam.put(tournamentTeam.Team__c, tournamentTeam.Group__c);
    }

    if (tournamentTeam.Group__c == groupOverview.groupName) {
      groupOverview.addTeamStats(new TeamStats(tournamentTeam));
    }
  }
}