force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batches/FinalsGeneratorBatchTest.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@isTest
private class FinalsGeneratorBatchTest {
  @isTest
  static void testFinalsGeneratorBatch() {
    // Create test data
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = 'TEST',
      Start_Date__c = Date.today()
    );
    insert tournament;
    List<Team__c> teams = new List<Team__c>();
    for (Integer i = 0; i < 4; i++) {
      teams.add(new Team__c(Name = 'Test Team ' + i, Code__c = 'T' + i));
    }
    insert teams;
    List<Match__c> semiFinalsMatches = new List<Match__c>();
    for (Integer i = 0; i < 2; i++) {
      semiFinalsMatches.add(
        new Match__c(
          Tournament__c = tournament.Id,
          Home_Team__c = teams[i * 2].Id,
          Away_Team__c = teams[i * 2 + 1].Id,
          Winner_Team__c = teams[i * 2].Id,
          Stage__c = StageUtility.SEMIFINAL_KO_STAGE,
          Date__c = Datetime.now().addDays(i)
        )
      );
    }

    TriggerHandler.bypass('MatchTriggerHandler');
    insert semiFinalsMatches;
    // Execute the batch
    Test.startTest();
    FinalsGeneratorBatch batch = new FinalsGeneratorBatch(
      tournament.Id,
      'testTransactionId'
    );
    Database.executeBatch(batch);
    Test.stopTest();
    // Verify the results
    List<Match__c> matches = [
      SELECT Id, Home_Team__c, Away_Team__c, Stage__c
      FROM Match__c
      WHERE
        Stage__c IN (
          :StageUtility.THIRD_PLACE_KO_STAGE,
          :StageUtility.FINAL_KO_STAGE
        )
    ];
    System.assertEquals(
      2,
      matches.size(),
      'Two matches should be created: one for third place and one for the final'
    );
    // Verify that matches are created correctly
    for (Match__c match : matches) {
      System.assert(
        match.Stage__c == StageUtility.THIRD_PLACE_KO_STAGE ||
          match.Stage__c == StageUtility.FINAL_KO_STAGE,
        'Match stage should be either Third Place or Final'
      );
    }
  }
}