force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batches/SemiFinalsGeneratorBatch.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-08-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class SemiFinalsGeneratorBatch implements Database.Batchable<SObject>, Database.Stateful {
  private Id tournamentId;
  private String originalTransactionId;

  public SemiFinalsGeneratorBatch(Id tournamentId, String loggerTransactionId) {
    this.tournamentId = tournamentId;
    this.originalTransactionId = loggerTransactionId;
  }

  public List<SObject> start(Database.BatchableContext bc) {
    List<Match__c> quarterFinalsMatches = [
      SELECT Id, Home_Team__c, Away_Team__c, Winner_Team__c
      FROM Match__c
      WHERE
        Tournament__c = :this.tournamentId
        AND Stage__c = :StageUtility.QUARTERFINAL_KO_STAGE
      WITH USER_MODE
    ];

    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Started semi-finals generator batch', quarterFinalsMatches);
    Logger.saveLog();

    return quarterFinalsMatches;
  }

  public void execute(Database.BatchableContext bc, List<SObject> scope) {
    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Executing semi-finals batch generator', scope);
    Savepoint savePoint = Database.setSavepoint();
    try {
      List<Match__c> quarterFinalsMatches = (List<Match__c>) scope;
      List<Match__c> semiFinalsMatches = generateSemiFinalsMatches(
        quarterFinalsMatches
      );
      Logger.info('semi-finals matches generated', semiFinalsMatches);
    } catch (Exception e) {
      Database.rollback(savePoint);
      Logger.error(
        'Error occurred while executing semi-finals generator batch. Rollbacking database changes',
        e
      );
    } finally {
      Logger.saveLog();
    }
  }

  public void finish(Database.BatchableContext bc) {
    AsyncApexJob job = [
      SELECT
        Id,
        Status,
        NumberOfErrors,
        JobItemsProcessed,
        TotalJobItems,
        CreatedBy.Email
      FROM AsyncApexJob
      WHERE Id = :bc.getJobId()
      WITH USER_MODE
    ];
    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Semi-finals generator batch finished', job);
    Logger.info('Queuing finals generator batch');
    FinalsGeneratorBatch nextBatch = new FinalsGeneratorBatch(
      this.tournamentId,
      this.originalTransactionId
    );
    Database.executeBatch(nextBatch);
    Logger.saveLog();
  }

  private List<Match__c> generateSemiFinalsMatches(
    List<Match__c> quarterFinalsMatches
  ) {
    List<Match__c> semiFinalsMatches = new List<Match__c>();

    // Generate dates
    Datetime date1 = Datetime.now().addDays(24);
    Datetime date2 = date1.addDays(1);
    Datetime[] dates = new List<Datetime>{ date1, date2 };
    Integer matchesSize = quarterFinalsMatches.size();

    for (Integer matchIndex = 0; matchIndex < matchesSize / 2; matchIndex++) {
      Match__c semiFinalMatch = new Match__c(
        Tournament__c = this.tournamentId,
        Home_Team__c = quarterFinalsMatches[matchIndex * 2].Winner_Team__c,
        Away_Team__c = quarterFinalsMatches[matchIndex * 2 + 1].Winner_Team__c,
        Date__c = dates[matchIndex],
        Stage__c = StageUtility.SEMIFINAL_KO_STAGE
      );
      MatchUtility.generateMatchResult(semiFinalMatch);
      semiFinalsMatches.add(semiFinalMatch);
    }

    insert as user semiFinalsMatches;

    return semiFinalsMatches;
  }
}