force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Home_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Flag_Code__c.field-meta.xml
<CustomField>
    <fullName>Flag_Code__c</fullName>
    <label>Flag Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/TournamentOverviewController.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 11-29-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class TournamentOverviewController {
  /**
   * @description
   * @author hbikry@salesforce.com | 11-29-2024
   * @param tournamentId
   * @return Map<String, List<MatchOverview>>
   **/
  @AuraEnabled
  public static Map<String, List<MatchOverview>> getKnockoutStageOverview(
    Id tournamentId
  ) {
    Map<String, List<MatchOverview>> matchOverviewByStage = new Map<String, List<MatchOverview>>();

    for (Match__c match : getMatches(tournamentId, StageUtility.KO_STAGES)) {
      if (!matchOverviewByStage.containsKey(match.Stage__c)) {
        matchOverviewByStage.put(match.Stage__c, new List<MatchOverview>());
      }

      matchOverviewByStage.get(match.Stage__c).add(new MatchOverview(match));
    }

    return matchOverviewByStage;
  }

  /**
   * @description
   * @author hbikry@salesforce.com | 11-29-2024
   * @param tournamentId
   * @param stages
   * @return List<Match__c>
   **/
  public static List<Match__c> getMatches(
    Id tournamentId,
    List<String> stages
  ) {
    return [
      SELECT
        Id,
        Stage__c,
        Date__c,
        Home_Team__r.Id,
        Home_Team__r.Name,
        Home_Team__r.Code__c,
        Home_Team__r.Flag_Code__c,
        Home_Team_Goals__c,
        Away_Team__r.Id,
        Away_Team__r.Name,
        Away_Team__r.Code__c,
        Away_Team__r.Flag_Code__c,
        Away_Team_Goals__c,
        Winner_Team__c,
        Draw__c
      FROM Match__c
      WHERE Tournament__c = :tournamentId AND Stage__c IN :stages
      WITH USER_MODE
      ORDER BY Date__c ASC
    ];
  }

  public class MatchOverview {
    @AuraEnabled
    public Id id;
    @AuraEnabled
    public String stage;
    @AuraEnabled
    public Datetime matchDate;
    @AuraEnabled
    public Id homeTeamId;
    @AuraEnabled
    public String homeTeamName;
    @AuraEnabled
    public String homeTeamCode;
    @AuraEnabled
    public String homeTeamFlagCode;
    @AuraEnabled
    public Integer homeTeamGoals;
    @AuraEnabled
    public Id awayTeamId;
    @AuraEnabled
    public String awayTeamName;
    @AuraEnabled
    public String awayTeamCode;
    @AuraEnabled
    public String awayTeamFlagCode;
    @AuraEnabled
    public Integer awayTeamGoals;
    @AuraEnabled
    public Id winnerTeamId;
    @AuraEnabled
    public Boolean draw;

    public MatchOverview(Match__c match) {
      this.Id = match.Id;
      this.stage = match.Stage__c;
      this.matchDate = match.Date__c;
      this.homeTeamId = match.Home_Team__r.Id;
      this.homeTeamName = match.Home_Team__r.Name;
      this.homeTeamCode = match.Home_Team__r.Code__c;
      this.homeTeamFlagCode = match.Home_Team__r.Flag_Code__c;
      this.homeTeamGoals = (Integer) match.Home_Team_Goals__c;
      this.awayTeamId = match.Away_Team__r.Id;
      this.awayTeamName = match.Away_Team__r.Name;
      this.awayTeamCode = match.Away_Team__r.Code__c;
      this.awayTeamFlagCode = match.Away_Team__r.Flag_Code__c;
      this.awayTeamGoals = (Integer) match.Away_Team_Goals__c;
      this.winnerTeamId = match.Winner_Team__c;
      this.draw = match.Draw__c;
    }
  }
}