force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Home_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/TeamOverviewControllerTest.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-11-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@isTest
private class TeamOverviewControllerTest {
  @isTest
  static void testGetTeamMatchesOverview() {
    // Create test data
    Tournament__c tournament1 = new Tournament__c(
      Name = 'Test Tournament 1',
      Code__c = 'TOUR1',
      Start_Date__c = Date.today()
    );
    Tournament__c tournament2 = new Tournament__c(
      Name = 'Test Tournament 2',
      Code__c = 'TOUR2',
      Start_Date__c = Date.today()
    );
    insert new List<Tournament__c>{ tournament1, tournament2 };
    Team__c team = new Team__c(Name = 'Test Team', Code__c = 'T1');
    insert team;
    List<Team__c> otherTeams = new List<Team__c>();
    for (Integer i = 0; i < 3; i++) {
      otherTeams.add(new Team__c(Name = 'Other Team ' + i, Code__c = 'O' + i));
    }
    insert otherTeams;
    List<Match__c> matches = new List<Match__c>();
    for (Integer i = 0; i < 3; i++) {
      matches.add(
        new Match__c(
          Tournament__c = (Math.mod(i, 2) == 0)
            ? tournament1.Id
            : tournament2.Id,
          Home_Team__c = (Math.mod(i, 2) == 0) ? team.Id : otherTeams[i].Id,
          Away_Team__c = (Math.mod(i, 2) == 0) ? otherTeams[i].Id : team.Id,
          Home_Team_Goals__c = 2,
          Away_Team_Goals__c = 1,
          Winner_Team__c = (Math.mod(i, 2) == 0) ? team.Id : otherTeams[i].Id,
          Stage__c = (Math.mod(i, 2) == 0)
            ? StageUtility.ROUND_1_GROUP_STAGE
            : StageUtility.ROUND_OF_16_KO_STAGE,
          Date__c = Date.today().addDays(i)
        )
      );
    }
    TriggerHandler.bypass('MatchTriggerHandler');
    insert matches;
    // Invoke the getTeamMatchesOverview method
    Test.startTest();
    Map<String, Map<String, List<MatchOverview>>> result = TeamOverviewController.getTeamMatchesOverview(
      team.Id
    );
    Test.stopTest();
    // Verify the results
    System.assertEquals(
      2,
      result.size(),
      'The number of tournaments should be 2'
    );
    for (String tournamentCode : result.keySet()) {
      Map<String, List<MatchOverview>> stageMap = result.get(tournamentCode);
      System.assertNotEquals(
        null,
        stageMap,
        'Stage map should not be null for tournament: ' + tournamentCode
      );
      System.assertNotEquals(
        0,
        stageMap.size(),
        'Stage map should not be empty for tournament: ' + tournamentCode
      );
      for (String stage : stageMap.keySet()) {
        List<MatchOverview> matchOverviews = stageMap.get(stage);
        System.assertNotEquals(
          null,
          matchOverviews,
          'Match overviews should not be null for stage: ' + stage
        );
        System.assertNotEquals(
          0,
          matchOverviews.size(),
          'Match overviews should not be empty for stage: ' + stage
        );
      }
    }
  }
}