force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Champion__c.field-meta.xml
<CustomField>
    <fullName>Champion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Champion</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Won Tournaments</relationshipLabel>
    <relationshipName>Won_Tournaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/handlers/AfterMatchTriggerHandler.cls
/**
 * @description       : After trigger handler for Match__c records
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-10-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class AfterMatchTriggerHandler {
  // Inserted/updated match record list
  private List<Match__c> newList;
  // Set for related tournament ids
  private Set<Id> tournamentIds = new Set<Id>();
  // List of related tournaments
  private Map<Id, Tournament__c> tournaments = new Map<Id, Tournament__c>();
  // List of related tournament teams
  private List<Tournament_Team__c> tournamentTeams = new List<Tournament_Team__c>();
  // For each related tournament, map tournament team by team Map<tournamentId, Map<teamId, Tournament_Team__c>>
  Map<Id, Map<Id, Tournament_Team__c>> tournamentTeamsByTeamMap = new Map<Id, Map<Id, Tournament_Team__c>>();
  // Map for tournament teams to update Map<tournamentId, Tournament_Team__c
  Map<Id, Tournament_Team__c> tournamentTeamsToUpdateMap = new Map<Id, Tournament_Team__c>();
  // List of tournaments to update
  List<Tournament__c> tournamentsToUpdate = new List<Tournament__c>();

  public AfterMatchTriggerHandler() {
    newList = (List<Match__c>) Trigger.new;
  }

  public void afterInsert() {
    handleRecords();
  }

  public void afterUpdate() {
    handleRecords();
  }

  /**
   * @description : Handle records after insert/update (update related records)
   * @author hbikry@salesforce.com | 12-09-2024
   **/
  public void handleRecords() {
    initUtils();

    // Sort match list by stage
    List<Match__c> matches = this.newList.clone();
    matches.sort(new MatchStageComparator());

    for (Match__c match : matches) {
      updateGroupStats(match);
      eliminateKnockedOutTeam(match);
      setChampion(match);
    }

    updateTournamentStage();

    update as user this.tournamentTeamsToUpdateMap.values();
    update as user this.tournamentsToUpdate;
  }

  /**
   * @description : Update tournament teams stats after a group stage match
   * @author hbikry@salesforce.com | 12-09-2024
   * @param match
   **/
  private void updateGroupStats(Match__c match) {
    if (!MatchUtility.isGroupStageMatch(match)) {
      return;
    }

    // Get updated tournament teams (calculate stats from match)
    List<Tournament_Team__c> updatedTournamentTeams = TournamentTeamUtility.getUpdatedTournamentTeamStats(
      match,
      this.tournamentTeamsByTeamMap
        .get(match.Tournament__c)
        .get(match.Home_Team__c), // Related tournament team for match home team
      this.tournamentTeamsByTeamMap
        .get(match.Tournament__c)
        .get(match.Away_Team__c) // Related tournament team for match away team
    );

    // Add updated tournament teams to update map
    this.tournamentTeamsToUpdateMap.put(
      match.Home_Team__c,
      updatedTournamentTeams[0] // [0] Home team
    );
    this.tournamentTeamsToUpdateMap.put(
      match.Away_Team__c,
      updatedTournamentTeams[1] // [1] Away team
    );
  }

  /**
   * @description : Mark loser team as eliminated after knockout stage match
   * @author hbikry@salesforce.com | 12-09-2024
   * @param match
   **/
  private void eliminateKnockedOutTeam(Match__c match) {
    if (!MatchUtility.isKnockoutStageMatch(match)) {
      return;
    }

    Tournament_Team__c homeTournamentTeam = this.tournamentTeamsByTeamMap
      .get(match.Tournament__c)
      .get(match.Home_Team__c);

    Tournament_Team__c awayTournamentTeam = this.tournamentTeamsByTeamMap
      .get(match.Tournament__c)
      .get(match.Away_Team__c);

    if (match.Winner_Team__c == match.Home_Team__c) {
      this.tournamentTeamsToUpdateMap.put(
        match.Away_Team__c,
        new Tournament_Team__c(Id = awayTournamentTeam.Id, Eliminated__c = true)
      );
    }

    if (match.Winner_Team__c == match.Away_Team__c) {
      this.tournamentTeamsToUpdateMap.put(
        match.Home_Team__c,
        new Tournament_Team__c(Id = homeTournamentTeam.Id, Eliminated__c = true)
      );
    }
  }

  /**
   * @description : Set champion team on tournament after final match
   * @author hbikry@salesforce.com | 12-09-2024
   * @param match
   **/
  private void setChampion(Match__c match) {
    if (match.Stage__c != StageUtility.FINAL_KO_STAGE) {
      return;
    }

    Tournament__c tournament = new Tournament__c(
      Id = match.Tournament__c,
      Champion__c = match.Winner_Team__c
    );

    this.tournamentsToUpdate.add(tournament);
  }

  private void updateTournamentStage() {
    Map<Id, Integer> getCountByTournamentsMap = MatchUtility.getCountByTournamentsMap(
      this.tournamentIds,
      StageUtility.GROUP_STAGES
    );

    for (Id tournamentId : this.tournamentIds) {
      // If already on knockout stage, skip
      if (
        TournamentStageUtility.tournamentInKnockoutStage(
          this.tournaments.get(tournamentId)
        )
      ) {
        continue;
      }

      Integer groupMatchesCount = getCountByTournamentsMap.get(tournamentId);

      // If group stage not yet finished, skip
      if (
        groupMatchesCount !=
        TournamentConfigurationUtility.getMaxMatchesInGroupStage()
      ) {
        continue;
      }

      // group stage finished -> update tournament stage to knockout stage

      this.tournamentsToUpdate.add(
        new Tournament__c(
          Id = tournamentId,
          Stage__c = TournamentStageUtility.KNOCKOUT_STAGE
        )
      );
    }
  }

  /**
   * @description : Populate utility maps and lists
   * @author hbikry@salesforce.com | 12-09-2024
   **/
  private void initUtils() {
    // Retrieve related tournament ids
    this.tournamentIds = MatchUtility.getRelatedTournamentIds(this.newList);

    // Retrieve related tournaments
    this.tournaments = TournamentUtility.getTournaments(tournamentIds);

    // Retrieve related tournament team records
    this.tournamentTeams = TournamentTeamUtility.getOverviewTournamentTeams(
      this.tournamentIds
    );

    // populate tournament teams by team map
    for (Tournament_Team__c tournamentTeam : this.tournamentTeams) {
      Id tournamentId = tournamentTeam.Tournament__c;
      if (!tournamentTeamsByTeamMap.containsKey(tournamentId)) {
        this.tournamentTeamsByTeamMap.put(
          tournamentId,
          new Map<Id, Tournament_Team__c>()
        );
      }

      this.tournamentTeamsByTeamMap.get(tournamentId)
        .put(tournamentTeam.Team__c, tournamentTeam);
    }
  }
}