force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Home_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Flag_Code__c.field-meta.xml
<CustomField>
    <fullName>Flag_Code__c</fullName>
    <label>Flag Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Draws__c.field-meta.xml
<CustomField>
    <fullName>Draws__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Draws</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Eliminated__c.field-meta.xml
<CustomField>
    <fullName>Eliminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eliminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_Against__c.field-meta.xml
<CustomField>
    <fullName>Goals_Against__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals Against</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Goals_For__c.field-meta.xml
<CustomField>
    <fullName>Goals_For__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goals For</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Losses__c.field-meta.xml
<CustomField>
    <fullName>Losses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Losses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Matches_Played__c.field-meta.xml
<CustomField>
    <fullName>Matches_Played__c</fullName>
    <formula>Draws__c +  Wins__c +  Losses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matches Played</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(  Wins__c  * 3 ) +  Draws__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Wins__c.field-meta.xml
<CustomField>
    <fullName>Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/apiResources/TournamentApiResource.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-09-2024
 * @last modified by  : hbikry@salesforce.com
 **/
@RestResource(urlMapping='/v1/tournaments/*')
global with sharing class TournamentApiResource {
  @HttpGet
  global static List<Tournament__c> handleGetRequests() {
    RestRequest req = RestContext.request;
    String[] uriParts = req.requestURI.split('/');

    if (uriParts.size() < 4) {
      // Handle /v1/tournaments (collection)
      return getTournaments();
    } else {
      // Handle /v1/tournaments/{code} (item)
      String tournamentCode = uriParts[3];

      return getTournament(tournamentCode);
    }
  }

  private static List<Tournament__c> getTournaments() {
    RestResponse res = RestContext.response;

    try {
      List<Tournament__c> tournaments = [
        SELECT Code__c, Name, Start_Date__c
        FROM Tournament__c
        WITH USER_MODE
      ];

      Logger.info('Returning response for /v1/tournaments', tournaments);

      return tournaments;
    } catch (Exception e) {
      res.statusCode = 500;
      res.responseBody = Blob.valueOf(
        JSON.serialize(new Map<String, String>{ 'error' => e.getMessage() })
      );

      Logger.error('Error occurred in /v1/tournaments', e);

      return null;
    } finally {
      Logger.saveLog();
    }
  }

  private static List<Tournament__c> getTournament(String tournamentCode) {
    RestResponse res = RestContext.response;

    try {
      List<Tournament__c> tournaments = [
        SELECT
          Id,
          Name,
          Code__c,
          Start_Date__c,
          (
            SELECT
              Team__c,
              Team__r.Name,
              Team__r.Code__c,
              Goals_For__c,
              Goals_Against__c,
              Goal_Difference__c,
              Wins__c,
              Losses__c,
              Draws__c,
              Matches_Played__c,
              Points__c,
              Eliminated__c
            FROM Tournament_Teams__r
          ),
          (
            SELECT
              Id,
              Stage__c,
              Date__c,
              Home_Team__r.Id,
              Home_Team__r.Name,
              Home_Team__r.Code__c,
              Home_Team__r.Flag_Code__c,
              Home_Team_Goals__c,
              Away_Team__r.Id,
              Away_Team__r.Name,
              Away_Team__r.Code__c,
              Away_Team__r.Flag_Code__c,
              Away_Team_Goals__c,
              Winner_Team__c,
              Draw__c
            FROM Matches__r
          )
        FROM Tournament__c
        WHERE Code__c = :tournamentCode
        WITH USER_MODE
        LIMIT 1
      ];

      if (tournaments.isEmpty()) {
        res.statusCode = 404;

        return null;
      }

      Logger.info(
        'Returning response for /v1/tournaments/' + tournamentCode,
        tournaments
      );

      return tournaments;
    } catch (Exception e) {
      res.statusCode = 500;
      res.responseBody = Blob.valueOf(
        JSON.serialize(new Map<String, String>{ 'error' => e.getMessage() })
      );

      Logger.error('Error occurred in /v1/tournaments/' + tournamentCode, e);

      return null;
    } finally {
      Logger.saveLog();
    }
  }
}