force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team_Goals__c.field-meta.xml
<CustomField>
    <fullName>Home_Team_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Team Goals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner_Team__c.field-meta.xml
<CustomField>
    <fullName>Winner_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner Team</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Home_Team__c</valueField>
        </filterItems>
        <filterItems>
            <field>Team__c.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Away_Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Winner Team)</relationshipLabel>
    <relationshipName>Matches_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description
  >This field is used to identify tournament objects in rest apis.</description>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/apiResources/MatchApiResourceTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class MatchApiResourceTest {
  @isTest
  static void testHandleGetRequestsForTournamentMatches() {
    String tournamentCode = 'TEST';
    String homeTeamCode = 'HME';
    String awayTeamCode = 'AWY';
    // Create test data
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = tournamentCode,
      Start_Date__c = Date.today()
    );
    insert tournament;
    Team__c homeTeam = new Team__c(Name = 'Home Team', Code__c = homeTeamCode);
    Team__c awayTeam = new Team__c(Name = 'Away Team', Code__c = awayTeamCode);
    insert new List<Team__c>{ homeTeam, awayTeam };
    TriggerHandler.bypass('MatchTriggerHandler');
    Match__c match = new Match__c(
      Tournament__c = tournament.Id,
      Stage__c = StageUtility.ROUND_1_GROUP_STAGE,
      Date__c = Datetime.now(),
      Home_Team__c = homeTeam.Id,
      Home_Team_Goals__c = 2,
      Away_Team__c = awayTeam.Id,
      Away_Team_Goals__c = 1,
      Winner_Team__c = homeTeam.Id,
      Draw__c = false
    );
    insert match;
    // Set up the mock HTTP request
    RestRequest req = new RestRequest();
    req.requestURI = '/v1/tournaments/' + tournamentCode + '/matches';
    req.httpMethod = 'GET';
    RestContext.request = req;
    // Call the method
    List<TournamentDTO.Match> result = MatchApiResource.handleGetRequests();
    // Verify the result
    System.debug(result);
    System.assertNotEquals(null, result, 'Result should not be null');
    System.assertEquals(1, result.size(), 'Result size should be 1');
    System.assertEquals(
      StageUtility.ROUND_1_GROUP_STAGE,
      result[0].stage,
      'Unexpected stage'
    );
    System.assertEquals(
      homeTeamCode,
      result[0].homeTeam,
      'Unexpected home team code'
    );
    System.assertEquals(
      2,
      result[0].homeTeamGoals,
      'Unexpected home team goals'
    );
    System.assertEquals(
      awayTeamCode,
      result[0].awayTeam,
      'Unexpected away team code'
    );
    System.assertEquals(
      1,
      result[0].awayTeamGoals,
      'Unexpected away team goals'
    );
  }

  @isTest
  static void testHandleGetRequestsForTeamMatches() {
    String tournamentCode = 'TEST';
    String homeTeamCode = 'HME';
    String awayTeamCode = 'AWY';
    // Create test data
    Tournament__c tournament = new Tournament__c(
      Name = 'Test Tournament',
      Code__c = tournamentCode,
      Start_Date__c = Date.today()
    );
    insert tournament;
    Team__c homeTeam = new Team__c(Name = 'Home Team', Code__c = homeTeamCode);
    Team__c awayTeam = new Team__c(Name = 'Away Team', Code__c = awayTeamCode);
    insert new List<Team__c>{ homeTeam, awayTeam };
    TriggerHandler.bypass('MatchTriggerHandler');
    Match__c match = new Match__c(
      Tournament__c = tournament.Id,
      Stage__c = StageUtility.ROUND_1_GROUP_STAGE,
      Date__c = Datetime.now(),
      Home_Team__c = homeTeam.Id,
      Home_Team_Goals__c = 2,
      Away_Team__c = awayTeam.Id,
      Away_Team_Goals__c = 1,
      Winner_Team__c = homeTeam.Id,
      Draw__c = false
    );
    insert match;
    // Set up the mock HTTP request
    RestRequest req = new RestRequest();
    req.requestURI =
      '/v1/tournaments/' +
      tournamentCode +
      '/matches/' +
      homeTeamCode;
    req.httpMethod = 'GET';
    RestContext.request = req;
    // Call the method
    List<TournamentDTO.Match> result = MatchApiResource.handleGetRequests();
    // Verify the result
    System.debug(result);
    System.assertNotEquals(null, result, 'Result should not be null');
    System.assertEquals(1, result.size(), 'Result size should be 1');
    System.assertEquals(
      StageUtility.ROUND_1_GROUP_STAGE,
      result[0].stage,
      'Unexpected stage'
    );
    System.assertEquals(
      homeTeamCode,
      result[0].homeTeam,
      'Unexpected home team code'
    );
    System.assertEquals(
      2,
      result[0].homeTeamGoals,
      'Unexpected home team goals'
    );
    System.assertEquals(
      awayTeamCode,
      result[0].awayTeam,
      'Unexpected away team code'
    );
    System.assertEquals(
      1,
      result[0].awayTeamGoals,
      'Unexpected away team goals'
    );
  }
}