force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away Team)</relationshipLabel>
    <relationshipName>Matches_Away</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage - Round 1</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 2</fullName>
            </value>
            <value>
                <fullName>Group Stage - Round 3</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Round of 16</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Quarter-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Semi-finals</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Third place</fullName>
            </value>
            <value>
                <fullName>Knockout Stage - Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Stage</fullName>
                <default>true</default>
                <label>Group Stage</label>
            </value>
            <value>
                <fullName>Knockout Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <label>Tournament Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tournament_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>(  Wins__c  * 3 ) +  Draws__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Qualification_Points__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Points__c</fullName>
    <description>Points used to qualify teams to later stages.</description>
    <formula>( Wins__c * 3 ) + Draws__c + Goal_Difference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qualification Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Tournament_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Group A</fullName>
    </customValue>
    <customValue>
        <fullName>Group B</fullName>
    </customValue>
    <customValue>
        <fullName>Group C</fullName>
    </customValue>
    <customValue>
        <fullName>Group D</fullName>
    </customValue>
    <customValue>
        <fullName>Group E</fullName>
    </customValue>
    <customValue>
        <fullName>Group F</fullName>
    </customValue>
    <customValue>
        <fullName>Group G</fullName>
    </customValue>
    <customValue>
        <fullName>Group H</fullName>
    </customValue>
    <masterLabel>Tournament Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batches/RoundOf16GeneratorBatch.cls
/**
 * @description       :
 * @author            : hbikry@salesforce.com
 * @group             :
 * @last modified on  : 12-08-2024
 * @last modified by  : hbikry@salesforce.com
 **/
public with sharing class RoundOf16GeneratorBatch implements Database.Batchable<SObject>, Database.Stateful {
  private Id tournamentId;
  private String originalTransactionId;

  public RoundOf16GeneratorBatch(Id tournamentId, String loggerTransactionId) {
    this.tournamentId = tournamentId;
    this.originalTransactionId = loggerTransactionId;
  }

  public List<SObject> start(Database.BatchableContext bc) {
    List<Tournament_Team__c> tournamentTeams = [
      SELECT Team__c, Group__c
      FROM Tournament_Team__c
      WHERE Tournament__c = :this.tournamentId
      WITH USER_MODE
      ORDER BY Group__c ASC, Points__c DESC, Qualification_Points__c DESC
    ];

    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Started round of 16 generator batch', tournamentTeams);
    Logger.saveLog();

    return tournamentTeams;
  }

  public void execute(Database.BatchableContext bc, List<SObject> scope) {
    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Executing round of 16 batch generator', scope);
    Savepoint savePoint = Database.setSavepoint();
    try {
      List<Tournament_Team__c> tournamentTeams = (List<Tournament_Team__c>) scope;
      // Generate round of 16 stage matches
      List<Match__c> roundOf16Matches = generateRoundOf16Matches(
        tournamentTeams
      );
      Logger.info('Round of 16 matches generated', roundOf16Matches);
    } catch (Exception e) {
      Database.rollback(savePoint);
      Logger.error(
        'Error occurred while executing round of 16 generator batch. Rollbacking database changes',
        e
      );
    } finally {
      Logger.saveLog();
    }
  }

  public void finish(Database.BatchableContext bc) {
    AsyncApexJob job = [
      SELECT
        Id,
        Status,
        NumberOfErrors,
        JobItemsProcessed,
        TotalJobItems,
        CreatedBy.Email
      FROM AsyncApexJob
      WHERE Id = :bc.getJobId()
      WITH USER_MODE
    ];
    Logger.setParentLogTransactionId(this.originalTransactionId);
    Logger.info('Round of 16 generator batch finished', job);
    Logger.info('Queuing quarter-finals generator batch');
    QuarterFinalsGeneratorBatch nextBatch = new QuarterFinalsGeneratorBatch(
      this.tournamentId,
      this.originalTransactionId
    );
    Database.executeBatch(nextBatch);
    Logger.saveLog();
  }

  private List<Match__c> generateRoundOf16Matches(
    List<Tournament_Team__c> tournamentTeams
  ) {
    // Map to hold the top two teams from each group
    Map<String, List<Tournament_Team__c>> topTeamsByGroup = new Map<String, List<Tournament_Team__c>>();
    // Loop over the records to determine the top two teams from each group
    for (Tournament_Team__c tt : tournamentTeams) {
      if (!topTeamsByGroup.containsKey(tt.Group__c)) {
        topTeamsByGroup.put(tt.Group__c, new List<Tournament_Team__c>());
      }

      if (topTeamsByGroup.get(tt.Group__c).size() < 2) {
        topTeamsByGroup.get(tt.Group__c).add(tt);
      }
    }

    // List to hold the Round of 16 matches
    List<Match__c> roundOf16Matches = new List<Match__c>();

    // Generate dates
    Datetime date1 = Datetime.now().addDays(15);
    Datetime date2 = date1.addDays(1);
    Datetime date3 = date2.addDays(1);
    Datetime date4 = date3.addDays(1);
    Datetime[] dates = new List<Datetime>{ date1, date2, date3, date4 };
    Integer groupsSize = GroupUtility.GROUPS.size();

    for (Integer groupIndex = 0; groupIndex < groupsSize / 2; groupIndex++) {
      String groupName = GroupUtility.GROUPS[groupIndex * 2];
      String nextGroupName = GroupUtility.nextGroup(groupName);

      List<Tournament_Team__c> groupTeams = topTeamsByGroup.get(groupName);
      List<Tournament_Team__c> nextGroupTeams = topTeamsByGroup.get(
        nextGroupName
      );

      Match__c match1 = new Match__c(
        Tournament__c = this.tournamentId,
        Home_Team__c = groupTeams[0].Team__c,
        Away_Team__c = nextGroupTeams[1].Team__c,
        Date__c = dates[(Integer) groupIndex / 2],
        Stage__c = StageUtility.ROUND_OF_16_KO_STAGE
      );
      MatchUtility.generateMatchResult(match1);
      roundOf16Matches.add(match1);

      Match__c match2 = new Match__c(
        Tournament__c = this.tournamentId,
        Home_Team__c = nextGroupTeams[0].Team__c,
        Away_Team__c = groupTeams[1].Team__c,
        Date__c = dates[(Integer) (groupIndex + groupsSize / 2) / 2],
        Stage__c = StageUtility.ROUND_OF_16_KO_STAGE
      );
      MatchUtility.generateMatchResult(match2);
      roundOf16Matches.add(match2);
    }

    insert as user roundOf16Matches;

    return roundOf16Matches;
  }
}